/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Query filter for parallel batch queries */
export interface QueryFilter {
  field: string
  op: string
  value: any
}
/** Batch query request */
export interface BatchQuery {
  path: string
  filters: Array<QueryFilter>
}
/** Parallel operation result */
export interface ParallelResult {
  success: boolean
  count: number
  error?: string
}
/** System resource info */
export interface SystemInfo {
  availableCores: number
  parallelEnabled: boolean
  recommendedBatchSize: number
}
export type NativeDB = NativeDb
export declare class NativeDb {
  /** Legacy constructor for backwards compatibility */
  constructor(path: string, wal: boolean)
  /** v4.5: Create database with options from JS */
  static newWithOptions(path: string, lockMode: string, durability: string, walBatchSize?: number | undefined | null, walFlushMs?: number | undefined | null, lockTimeoutMs?: number | undefined | null): NativeDb
  /** Get system resource information for adaptive parallelism */
  getSystemInfo(): SystemInfo
  /** v4.5: Explicit sync for durability */
  sync(): void
  /** v4.5: Get current WAL status */
  walStatus(): any
  /** v4.5: Explicitly release resources (locks, WAL handles) */
  close(): void
  /** Legacy load (maintained for compatibility) */
  load(): void
  save(): void
  /** Execute batch set operations in parallel when beneficial */
  batchSetParallel(operations: Array<[string, any]>): ParallelResult
  /** Parallel filter/query on a collection */
  parallelQuery(path: string, filters: Array<QueryFilter>): any
  /** Parallel aggregation operations */
  parallelAggregate(path: string, operation: string, field?: string | undefined | null): any
  /** Perform a parallel left outer join between two collections (lookup) */
  parallelLookup(leftPath: string, rightPath: string, leftField: string, rightField: string, asField: string): any
  get(path: string): any
  getMany(paths: Array<string>): Array<any>
  set(path: string, value: any): void
  has(path: string): boolean
  delete(path: string): void
  push(path: string, value: any): void
  offload(path: string): string
  restore(path: string): boolean
  /**
   * Execute a full query pipeline entirely in Rust: filter → sort → skip → limit → select
   * This is the primary query method — replaces JS-side QueryBuilder processing
   */
  executeQuery(path: string, filtersJson: string, sortJson?: string | undefined | null, limit?: number | undefined | null, skip?: number | undefined | null, selectFields?: Array<string> | undefined | null): any
  /**
   * Fast string-based query — returns JSON string instead of Value
   * This avoids N-API's recursive Value→JS serialization overhead.
   * JS side does a single JSON.parse() which is much faster.
   */
  executeQueryFast(path: string, filtersJson: string, sortJson?: string | undefined | null, limit?: number | undefined | null, skip?: number | undefined | null, selectFields?: Array<string> | undefined | null): string
  /** Fast string-based aggregation — returns JSON string instead of Value */
  executeAggregateFast(path: string, filtersJson: string, operation: string, field?: string | undefined | null): string
  /** Execute aggregation with filters entirely in Rust */
  executeAggregate(path: string, filtersJson: string, operation: string, field?: string | undefined | null): any
  /**
   * Pull (remove) items from an array — O(N) single pass with HashSet lookup
   * Returns the number of items removed
   */
  pullItems(path: string, items: Array<any>): number
  /**
   * Push multiple items to an array at once — single lock acquisition
   * Returns the number of items actually added (skips duplicates)
   */
  pushBatch(path: string, items: Array<any>): number
  /** Configure memory management for smart offloading */
  configureMemory(maxMemory: string, coldStorageDir?: string | undefined | null, evictionThresholdPct?: number | undefined | null, evictionTargetPct?: number | undefined | null): void
  /**
   * Check memory pressure and auto-evict if needed
   * Returns list of keys that were evicted
   */
  checkMemoryPressure(): Array<string>
  /** Get memory statistics */
  memoryStats(): any
  registerIndex(name: string, field: string): void
  updateIndex(name: string, key: any, path: string, isDelete: boolean): void
  findIndexPaths(name: string, key: any): Array<string>
  clearIndex(name: string): void
  findIndexRange(name: string, start?: any | undefined | null, end?: any | undefined | null): Array<string>
  registerSchema(path: string, schemaJson: string): void
  validatePath(path: string, value: any): void
  beginTransaction(): void
  commitTransaction(): void
  rollbackTransaction(): void
  createSavepoint(name: string): void
  rollbackToSavepoint(name: string): void
}
