/* auto-generated by NAPI-RS — updated by v6: prebuilds/ layout */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

// All local .node prebuilds live in prebuilds/ — keeps root directory clean
const PREBUILDS_DIR = join(__dirname, 'prebuilds')

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

/** Resolve path to a local prebuild .node file inside prebuilds/ */
function prebuild(name) {
  return join(PREBUILDS_DIR, name)
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(prebuild('index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.android-arm64.node'))
          } else {
            nativeBinding = require('jsondb-high-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(prebuild('index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.android-arm-eabi.node'))
          } else {
            nativeBinding = require('jsondb-high-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break

  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(prebuild('index.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.win32-x64-msvc.node'))
          } else {
            nativeBinding = require('jsondb-high-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(prebuild('index.win32-ia32-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.win32-ia32-msvc.node'))
          } else {
            nativeBinding = require('jsondb-high-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(prebuild('index.win32-arm64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.win32-arm64-msvc.node'))
          } else {
            nativeBinding = require('jsondb-high-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break

  case 'darwin':
    localFileExisted = existsSync(prebuild('index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require(prebuild('index.darwin-universal.node'))
      } else {
        nativeBinding = require('jsondb-high-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(prebuild('index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.darwin-x64.node'))
          } else {
            nativeBinding = require('jsondb-high-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(prebuild('index.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.darwin-arm64.node'))
          } else {
            nativeBinding = require('jsondb-high-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break

  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(prebuild('index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require(prebuild('index.freebsd-x64.node'))
      } else {
        nativeBinding = require('jsondb-high-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break

  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(prebuild('index.linux-x64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-x64-musl.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(prebuild('index.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-x64-gnu.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(prebuild('index.linux-arm64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-arm64-musl.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(prebuild('index.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-arm64-gnu.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(prebuild('index.linux-arm-musleabihf.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-arm-musleabihf.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(prebuild('index.linux-arm-gnueabihf.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-arm-gnueabihf.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(prebuild('index.linux-riscv64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-riscv64-musl.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(prebuild('index.linux-riscv64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require(prebuild('index.linux-riscv64-gnu.node'))
            } else {
              nativeBinding = require('jsondb-high-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(prebuild('index.linux-s390x-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require(prebuild('index.linux-s390x-gnu.node'))
          } else {
            nativeBinding = require('jsondb-high-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break

  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  // --- Tier 2: Build from source ---
  try {
    const { buildOnDemand } = require('./scripts/build-on-demand.js')
    const builtPath = buildOnDemand()
    if (builtPath) {
      nativeBinding = require(builtPath)
    }
  } catch (buildErr) {
    loadError = loadError || buildErr
  }
}

if (!nativeBinding) {
  // --- Tier 3: WASM fallback ---
  try {
    nativeBinding = require('./wasm-shim.js')
    if (nativeBinding && nativeBinding.NativeDb) {
      console.warn(
        '[jsondb-high] Running in WASM fallback mode. ' +
        'Performance will be reduced (no parallelism, no file locking). ' +
        'Install Rust (https://rustup.rs/) for native performance.'
      )
    } else {
      nativeBinding = null
    }
  } catch (wasmErr) {
    const reason = loadError ? loadError.message : 'no load error recorded'
    throw new Error(
      `Failed to load jsondb-high:\n` +
      `  Native: ${reason}\n` +
      `  WASM: ${wasmErr && wasmErr.message ? wasmErr.message : wasmErr}\n` +
      `Install Rust (https://rustup.rs/) or ensure the WASM package is built.`
    )
  }
}

if (!nativeBinding) {
  throw new Error(
    'Failed to load jsondb-high: no native binary, build from source failed, and WASM fallback unavailable.'
  )
}

const { NativeDb } = nativeBinding

module.exports.NativeDb = NativeDb
