/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Query filter for parallel batch queries */
export interface QueryFilter {
  field: string
  op: string
  value: any
}
/** Batch query request */
export interface BatchQuery {
  path: string
  filters: Array<QueryFilter>
}
/** Parallel operation result */
export interface ParallelResult {
  success: boolean
  count: number
  error?: string
}
/** System resource info */
export interface SystemInfo {
  availableCores: number
  parallelEnabled: boolean
  recommendedBatchSize: number
}
export type NativeDB = NativeDb
export declare class NativeDb {
  constructor(path: string, wal: boolean)
  /** Get system resource information for adaptive parallelism */
  getSystemInfo(): SystemInfo
  load(): void
  save(): void
  /**
   * Execute batch set operations in parallel when beneficial
   * Automatically falls back to sequential for small batches
   */
  batchSetParallel(operations: Array<[string, any]>): ParallelResult
  /**
   * Parallel filter/query on a collection
   * Uses rayon for CPU-bound filtering when data is large enough
   */
  parallelQuery(path: string, filters: Array<QueryFilter>): any
  /** Parallel aggregation operations */
  parallelAggregate(path: string, operation: string, field?: string | undefined | null): any
  get(path: string): any
  set(path: string, value: any): void
  has(path: string): boolean
  delete(path: string): void
  push(path: string, value: any): void
}
