/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type NativeDB = NativeDb
export declare class NativeDb {
  constructor(path: string, wal: boolean)
  load(): void
  save(): void
  get(path: string): any
  set(path: string, value: any): void
  has(path: string): boolean
  delete(path: string): void
  push(path: string, value: any): void
}
